name: 'file-sync'
description: 'Sync files between repositories'
inputs:
  token:
    description: 'GitHub Token or PAT'
    required: true
  repo:
    description: 'Source GitHub repo'
    required: true
  repo-branch:
    description: 'Source GitHub repo branch name'
    required: false
    default: 'main'
  destination-repos:
    description: 'List of destination repos'
    required: false
  destination-repos-regex:
    description: 'Regex to match destination repos'
    required: false
  destination-repos-exclude:
    description: 'List of destination repos to exclude'
    required: false
  files:
    description: 'List of files to sync'
    required: true
  delete-files:
    description: 'List of files to delete'
    required: false
  target-branch:
    description: 'Target branch for pull request'
    required: false
    default: 'main'
  pull-request-branch:
    description: 'Branch to push changes'
    required: false
    default: 'file-sync'
  pull-request-draft:
    description: 'Open the pull request in draft status'
    required: false
    type: boolean
    default: 'false'
  user:
    description: 'Git username'
    required: false
    default: 'file-sync'
  email:
    description: 'Git email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  commit-message:
    description: 'Commit message to use when updating files'
    required: false
    default: 'Updated by file-sync'

runs:
  using: "composite"
  steps:
    - run: 'cp ${{ github.action_path }}/requirements.txt . || true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_SOURCE_REPO: ${{ inputs.repo }}
        INPUT_SOURCE_REPO_BRANCH: ${{ inputs.repo-branch }}
        INPUT_DESTINATION_REPOS: ${{ inputs.destination-repos }}
        INPUT_DESTINATION_REPOS_REGEX: ${{ inputs.destination-repos-regex }}
        INPUT_DESTINATION_REPOS_EXCLUDE: ${{ inputs.destination-repos-exclude }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_DELETE_FILES: ${{ inputs.delete-files }}
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        INPUT_PULL_REQUEST_BRANCH: ${{ inputs.pull-request-branch }}
        INPUT_PULL_REQUEST_DRAFT: ${{ inputs.pull-request-draft }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_CURRENT_REPOSITORY: ${{ github.repository }}
