name: 'file-sync'
description: 'Sync files between repositories'
inputs:
  token:
    description: 'GitHub Token or PAT'
    required: false
    default: ''
  repo:
    description: 'Source GitHub repo'
    required: true
  files:
    description: 'List of files to sync'
    required: true
  target-branch:
    description: 'Target branch for pull request'
    required: false
    default: 'main'
  pull-request-branch:
    description: 'Branch to push changes'
    required: false
    default: 'file-sync'
  user:
    description: 'Git username'
    required: false
    default: 'file-sync'
  email:
    description: 'Git email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  commit-message:
    description: 'Commit message to use when updating files'
    required: false
    default: 'Updated by file-sync'
  delete-files:
    description: 'List of files to delete'
    required: true

runs:
  using: "composite"
  steps:
    - run: 'cp ${{ github.action_path }}/requirements.txt .'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        INPUT_PULL_REQUEST_BRANCH: ${{ inputs.pull-request-branch }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_DELETE_FILES: ${{ inputs.delete-files }}
