name: 'file-sync'
inputs:
  token:
    description: 'access token'
    required: false
  files:
    description: 'list of files'
    required: false
runs:
  using: "composite"
  steps:
    - run: go run main.go
      shell: bash