name: 'file-sync'
inputs:
  token:
    description: 'access token'
    required: false
  repo:
    description: 'source repo'
    required: false
  files:
    description: 'list of files'
    required: false
runs:
  using: "composite"
  steps:
    - run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_REPO: ${{ inputs.repo }}