on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reeves122/file-sync@fb61a74122b447e32b1ba30a86180c825604e7de
        with:
          token: ${{ secrets.FILE_SYNC_PAT }}