on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reeves122/file-sync@e4d8ec27d52339cfcabf69679f8e6853d714fe31
        with:
          token: ${{ secrets.FILE_SYNC_PAT }}
          files: |
            file1=foo1
            file2=foo2
            file3=foo3