on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reeves122/file-sync@50718d52413763c73b2a25fda1300ccb55491263