on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reeves122/file-sync@76a719dcd1c3f92037778080880f333feb232415
        with:
          token: ${{ secrets.FILE_SYNC_PAT }}