on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Go Run
        run: |
          go mod download
          go run main.go