on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Go Run
        run: |
          git status
          git fetch
          git checkout integration-test
          cat foo-new-file.txt
